initial commit
gridsuite/report-server pull request #1
Opened 2021-05-19 10:59 UTC by JacquesBorsenberger

Signed-off-by: jacqbors <jacques.borsenberger@rte-france.com>

2021-05-19 13:24 UTC, JacquesBorsenberger commented
WIP, i need to add indexes :)

2021-06-11 11:28 UTC, jonenst commented on maven.yml
> +name: CI
remove this spurious copy of .github/workflows/maven.yml

2021-06-11 11:29 UTC, jonenst commented on src/main/java/org/gridsuite/report/server/ReportApi.java
> + * @author Geoffroy Jamgotchian <geoffroy.jamgotchian at rte-france.com>
author ?

2021-06-11 11:30 UTC, jonenst commented on src/main/java/org/gridsuite/report/server/DataSourceConfig.java
> + * @author Franck Lecuyer <franck.lecuyer at rte-france.com>
author ?

2021-06-11 11:30 UTC, jonenst commented on src/main/java/org/gridsuite/report/server/ReportApplication.java
> + * @author Geoffroy Jamgotchian <geoffroy.jamgotchian at rte-france.com>
author ?

2021-06-11 11:31 UTC, jonenst commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +@ComponentScan(basePackageClasses = ReportService.class)
I don't think you need the componentScan, if this class in included the package has already been scanned

2021-06-11 11:39 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/WebFluxConfig.java
> +public class WebFluxConfig implements WebFluxConfigurer {
Why do you mix mvc et webflux ?

2021-06-11 11:57 UTC, SlimaneAmar commented
I think it is necessary to use a non-blocking approach (web flux) because the logs have a large size

2021-06-11 12:23 UTC, jonenst commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +    ReportService self;
not used

2021-06-11 12:27 UTC, jonenst commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +    @Transactional
put the @Transaction on a method in the reportRepository interface ?

2021-06-11 12:29 UTC, jonenst commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +    @Transactional
Actually it's already there in crudrepositroy so I don't think you need it here ?

2021-06-11 12:30 UTC, jonenst commented on src/main/java/org/gridsuite/report/server/configs/ReportSwaggerConfig.java
> + * @author Geoffroy Jamgotchian <geoffroy.jamgotchian at rte-france.com>
author

2021-06-11 12:52 UTC, SlimaneAmar requested changes

2021-06-11 12:52 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/entities/ReportEntity.java
> +    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
To avoid to load all  `TreeReportEntity` it's better to have an association `ManyToOne`
And normally we will access the `TreeReportEntity` individually

2021-06-11 13:07 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/entities/ReportEntity.java
> +public class ReportEntity {
Need to implement ` Persistable<ID> ` in order to avoid a select for each creation because the id manually generated

2021-06-11 14:17 UTC, SlimaneAmar requested changes

2021-06-11 14:17 UTC, SlimaneAmar commented on pom.xml
> +            <artifactId>powsybl-contingency-api</artifactId>
?
powsybl-commons

2021-06-11 14:50 UTC, JacquesBorsenberger commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +    @PutMapping(value = "report/{id}", consumes = MediaType.APPLICATION_JSON_VALUE)
we don't know if a report already exists, so we don't know if is a creation or an update,

2021-06-11 15:18 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +    @ApiOperation(value = "Get report by id", response = Collection.class)
Not a collection

2021-06-14 06:04 UTC, jonenst commented on pom.xml
> +            <groupId>com.h2database</groupId>
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.gridsuite:gridsuite-report-server:jar:1.0.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.h2database:h2:jar -> duplicate declaration of version (?) @ line 181, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

2021-06-14 06:37 UTC, jonenst commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +            reportRepository.save(reportEntity.get());
why save an already managed entity ?

2021-06-14 06:39 UTC, jonenst commented on src/main/java/org/gridsuite/report/server/entities/ReportElementEntity.java
> +public class ReportElementEntity {
add @table annotations to avoid the name "ReportElementEntity" for the table

2021-06-14 06:52 UTC, jonenst commented
"I think it is necessary to use a non-blocking approach (web flux) because the logs have a large size"
Maybe but in a later PR ?

2021-06-14 10:43 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/repositories/TreeReportRepository.java
> +public interface TreeReportRepository extends JpaRepository<TreeReportEntity, UUID> {
We can simplify ?

```
@Repository
public interface TreeReportRepository extends JpaRepository<TreeReportEntity, UUID> {
    List<TreeReportEntity> findAllByReportId(UUID uuid);

    List<TreeReportEntity> findAllByReportIdAndName(UUID uuid, String name);
}
```

2021-06-14 10:43 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/entities/TreeReportEntity.java
> +    @Index(name = "treeReport_idnode_idx", columnList = "idNode"),
index automatically created for a primary key ?

2021-06-14 12:30 UTC, jonenst commented on pom.xml
> +            <version>1.18.12</version>
remove version

2021-06-29 06:55 UTC, JacquesBorsenberger commented on src/main/java/org/gridsuite/report/server/WebFluxConfig.java
> +public class WebFluxConfig implements WebFluxConfigurer {
removed

2021-06-30 13:29 UTC, SlimaneAmar approved these changes

2021-06-30 13:51 UTC, merged