Add supervision controller
gridsuite/report-server pull request #48
Opened 2023-09-05 11:55 UTC by Meklo

2023-09-08 13:08 UTC, sBouzols commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +        reportsIds.forEach(report -> {
```suggestion
        reportsIds.forEach(reportId -> {
```

2023-09-08 13:08 UTC, sBouzols commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +            List<TreeReportEntity> treeReports = treeReportRepository.findAllByReportId(report);
Is it possible to get multiple reports with only one Uuid ???

2023-09-08 13:11 UTC, sBouzols commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +    public void deleteSubreporterByName(List<UUID> reportsIds, String name) {
What represents `reportsIds` here ? a collection of reports to search in ?

2023-09-08 13:15 UTC, sBouzols commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +                    if (name.equals(subTreeReport.getName())) {
Maybe we could add a `find...` query which takes the name in a WHERE clause to avoid doing this check in java ?

2023-09-08 13:18 UTC, sBouzols commented on src/main/java/org/gridsuite/report/server/repositories/TreeReportRepository.java
> +    void deleteAllByIdNode(UUID uuid);
Why this add ?

2023-09-08 13:18 UTC, sBouzols commented on src/test/resources/reportSimulators.json
> +}
add new line

2023-09-08 13:18 UTC, sBouzols commented on src/test/resources/expectedDeletedSimulators.json
> +]
add new line

2023-09-08 13:19 UTC, sBouzols commented on src/main/java/org/gridsuite/report/server/SupervisionController.java
> +
```suggestion
/**
 * @author Hugo Marcellin <hugo.marcelin at rte-france.com>
 */
```

2023-09-08 13:20 UTC, sBouzols reviewed
some comments

2023-09-11 11:45 UTC, Meklo commented on src/main/java/org/gridsuite/report/server/repositories/TreeReportRepository.java
> +    void deleteAllByIdNode(UUID uuid);
It was transient, forgot to clean it

2023-09-11 11:50 UTC, Meklo commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +            List<TreeReportEntity> treeReports = treeReportRepository.findAllByReportId(report);
There's only one Report for a given node but here we are gathering a report's TreeReports, which can be numerous

2023-09-11 11:51 UTC, Meklo commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +            List<TreeReportEntity> treeReports = treeReportRepository.findAllByReportId(report);
I could directly stream from the find instead of storing it in a List I reckon

2023-09-11 11:53 UTC, Meklo commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +                    if (name.equals(subTreeReport.getName())) {
That would indeed be more optimized, that said we would need it make a join on itself since the reportId is stored in those subreports parents

2023-09-13 16:16 UTC, SlimaneAmar requested changes

2023-09-13 16:16 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +        subreportsKey.entrySet().forEach(reportKeys -> deleteTreeReportByName(reportKeys.getKey(), reportKeys.getValue()));
`        identifiers.forEach((key, value) -> deleteTreeReport(key, value));`

2023-09-18 11:46 UTC, Meklo commented on src/test/resources/reportSimulators.json
> +}
Done

2023-09-18 11:46 UTC, Meklo commented on src/test/resources/expectedDeletedSimulators.json
> +]
I've deleted this file in the end

2023-09-18 11:47 UTC, Meklo commented on src/main/java/org/gridsuite/report/server/SupervisionController.java
> +
I've deleted the file in the end because deleteTreereports can be useful for regular operations

2023-09-18 11:48 UTC, Meklo commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +    public void deleteSubreport(Map<UUID, String> subreportsKey) {
Done, I've renamed all the chain from study server to here because it's not really about subreports in the end

2023-09-18 11:48 UTC, Meklo commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +        subreportsKey.entrySet().forEach(reportKeys -> deleteTreeReportByName(reportKeys.getKey(), reportKeys.getValue()));
Done

2023-09-18 13:24 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +    public void deleteTreeReport(UUID reportId, String computationSubreportKey) {
Make private

2023-09-18 13:24 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +    public void deleteTreeReport(UUID reportId, String computationSubreportKey) {
`computationSubreportKey` computation is not a unknown notion for report server.
Rename by `name` ?

2023-09-18 17:01 UTC, Meklo commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +    public void deleteTreeReport(UUID reportId, String computationSubreportKey) {
Done

2023-09-19 15:39 UTC, sBouzols commented on src/main/java/org/gridsuite/report/server/repositories/TreeReportRepository.java
> +    List<TreeReportEntity> findAllByReportIdAndName(UUID uuid, String name);
If we add a WHERE clause over Name, maybe we should add an index in database if it's often called?

2023-09-20 09:07 UTC, Meklo commented on src/main/java/org/gridsuite/report/server/repositories/TreeReportRepository.java
> +    List<TreeReportEntity> findAllByReportIdAndName(UUID uuid, String name);
I reckon it'd become interesting to do so once this method is used outside supervision use

2023-09-20 13:19 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/repositories/TreeReportRepository.java
> +    List<TreeReportEntity> findAllByReportIdAndName(UUID uuid, String name);
Already exist ?

2023-09-20 14:17 UTC, Meklo commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +        service.deleteTreeReports(treeReportsKeys);
I've opted for identifiers

2023-09-21 07:24 UTC, sBouzols approved these changes

2023-09-21 09:17 UTC, merged