WIP Separate computation logs from modification logs
gridsuite/report-server pull request #60
Opened 2023-11-03 16:23 UTC by dbraquart

2023-11-17 15:58 UTC, EstherDarkish requested changes

2023-11-17 15:58 UTC, EstherDarkish commented on src/main/java/org/gridsuite/report/server/ReportService.java
>      }
We should never mix a check (size equals to) and a job (delete something) inside of a `if` declaration. The job should be on its own line, because as is, it is hidden.

2023-11-20 16:29 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +            return CollectionUtils.isEmpty(subReporters) ?
CollectionUtils.isEmpty ?
The list could be null ?
Remove the test ?

2023-11-20 16:29 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +                                                         @Parameter(description = "Kind of matching filter to apply to task key.") @RequestParam(name = "taskKeyFilterMatchingType", required = false)
I think it's better to rename this notion `taskKeyFilter` by `reportNameFilter` and `reportTypeFilter`
It'not a `taskKey` !

2023-11-20 16:29 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +    public enum TaskKeyFilterMatchingType {
`FilterMatchingType` ?

2023-11-20 16:29 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +        List<TreeReportEntity> allTreeReportsInReport = treeReportRepository.findAllByReportIdOrderByNanos(id);
ByNanos ?

2023-11-21 12:01 UTC, dbraquart commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +            return CollectionUtils.isEmpty(subReporters) ?
it cannot be null indeed, but it can be empty

2023-11-22 11:13 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +            return subReporters.isEmpty() ?
Remove the test

2023-11-22 13:15 UTC, dbraquart commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +            return subReporters.isEmpty() ?
I need it.
There are some cases where we return no subReporters. Before this PR, it was no visible because in theses cases a computation subReporter was here.
It is an issue to have a report with no NetworkModification subReporter (even empty). This test here is a workaround.

2023-11-23 08:09 UTC, SlimaneAmar approved these changes

2023-11-23 09:12 UTC, EstherDarkish approved these changes
Ok, but please no deletion hidden in a "if"

2023-11-23 11:43 UTC, merged