Dynamic report severity list
gridsuite/report-server pull request #68
Opened 2023-12-27 09:51 UTC by lilian-houdelet

2023-12-29 17:54 UTC, flomillot requested changes
Please update the swagger doc of the endpoints

2023-12-29 17:54 UTC, flomillot commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +        var report = getReport(reportId, withElements, Stream.of(SeverityLevel.values()).map(Enum::name).collect(Collectors.toSet()), reportNameFilter, reportNameMatchingType);
Can you extract the stream ? It's not easily readable

2023-12-29 17:54 UTC, flomillot commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +        var report = getSubReport(reporterId, Stream.of(SeverityLevel.values()).map(Enum::name).collect(Collectors.toSet()));
Same

2023-12-29 17:54 UTC, flomillot commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +        reportSeverityList.addAll(reporterModel.getReports().stream().map(report -> report.getValue("reportSeverity").getValue().toString()).distinct().toList());
Please refactor to remove duplicate lines

2024-01-02 13:15 UTC, dbraquart requested changes
As discussed, severity list must not be calculated each time by reading the reports tree. We have to save it at insertion time, and then use it into the Front.
No REST api change is required.

2024-01-05 15:46 UTC, flomillot commented on src/test/java/org/gridsuite/report/server/ReportControllerTest.java
>          // Expect 4 batched inserts only and no updates
```suggestion
        // Expect 5 batched inserts only and no updates
```

2024-01-05 15:46 UTC, flomillot commented on src/main/java/org/gridsuite/report/server/ReportService.java
> +        treeReportEntity.getValues().add(new ReportValueEmbeddable("severityList", severityList(reporterModel), TypedValue.SEVERITY));
Can you do everything in the constructor ?

2024-01-05 16:38 UTC, flomillot approved these changes

2024-01-05 16:38 UTC, flomillot commented
Code OK

2024-01-09 16:41 UTC, dbraquart requested changes
code: ok
tests: ok, but we have to discuss the compatibility, how we treat existing logs

2024-01-16 15:00 UTC, dbraquart approved these changes
code: ok
tests: ok

Finally we dont plan any logs migration (but node invalidation). Then we can merge as is.

2024-01-16 17:25 UTC, merged