Upgrade to powsybl dependencies 2024.2.0
gridsuite/report-server pull request #85
Opened 2024-07-22 09:28 UTC by FranckLecuyer

2024-07-24 09:56 UTC, Tristan-WorkGH requested changes

2024-07-24 09:56 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +    public ResponseEntity<List<ReportNodeImpl>> getReport(@PathVariable("id") UUID id,
why do you need the implementation instead of the interface?

2024-07-24 14:12 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +    public ResponseEntity<List<ReportNodeImpl>> getReport(@PathVariable("id") UUID id,
Same thing has been done in powsybl-core, in this PR : https://github.com/powsybl/powsybl-core/pull/3011
when they upgrade to ReportNode V2.1 ...

2024-07-26 14:26 UTC, Tristan-WorkGH requested changes
We can minimize change & impact on our code by only changing for Spring & Jackson (de)serialization.

2024-07-26 14:26 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +                ResponseEntity.ok().contentType(MediaType.APPLICATION_JSON).body(service.getEmptyReport(id, defaultName).getChildren().stream().map(r -> (ReportNodeImpl) r).toList()) :
```suggestion
                ResponseEntity.ok().contentType(MediaType.APPLICATION_JSON).body(service.getEmptyReport(id, defaultName).getChildren().stream().map(ReportNodeImpl::cast).toList()) :
```

2024-07-26 14:26 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +                ResponseEntity.ok().contentType(MediaType.APPLICATION_JSON).body(subReporters.stream().map(r -> (ReportNodeImpl) r).toList());
```suggestion
                ResponseEntity.ok().contentType(MediaType.APPLICATION_JSON).body(subReporters.stream().map(ReportNodeImpl::cast).toList());
```

2024-07-26 14:26 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +            return ResponseEntity.ok().contentType(MediaType.APPLICATION_JSON).body(service.getEmptyReport(id, defaultName).getChildren().stream().map(r -> (ReportNodeImpl) r).toList());
```suggestion
            return ResponseEntity.ok().contentType(MediaType.APPLICATION_JSON).body(service.getEmptyReport(id, defaultName).getChildren().stream().map(ReportNodeImpl::cast).toList());
```

2024-07-26 14:26 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +                    .body(service.getSubReport(id, severityLevels).getChildren().stream().map(r -> (ReportNodeImpl) r).toList());
```suggestion
                    .body(service.getSubReport(id, severityLevels).getChildren().stream().map(ReportNodeImpl::cast).toList());
```

2024-07-26 14:26 UTC, Tristan-WorkGH commented on src/test/java/org/gridsuite/report/server/ReportControllerTest.java
> +        List<ReportNodeImpl> actualReportNodeList = objectMapper.readValue(result.getResponse().getContentAsString(), new TypeReference<>() { });
```suggestion
        List<ReportNode> expectedReportNodeList = objectMapper.readValue(expectedContent, new TypeReference<List<ReportNodeImpl>>() { });
        List<ReportNode> actualReportNodeList = objectMapper.readValue(result.getResponse().getContentAsString(), new TypeReference<List<ReportNodeImpl>>() { });
```

2024-07-26 14:26 UTC, Tristan-WorkGH commented on src/test/java/org/gridsuite/report/server/utils/TestUtils.java
> +    public static void assertReportListsAreEqualIgnoringIds(List<ReportNodeImpl> expectedNodeList, List<ReportNodeImpl> actualNodeList) {
```suggestion
    public static void assertReportListsAreEqualIgnoringIds(List<ReportNode> expectedNodeList, List<ReportNode> actualNodeList) {
```

2024-07-29 06:39 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +                ResponseEntity.ok().contentType(MediaType.APPLICATION_JSON).body(service.getEmptyReport(id, defaultName).getChildren().stream().map(r -> (ReportNodeImpl) r).toList()) :
ok

2024-07-29 06:39 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +            return ResponseEntity.ok().contentType(MediaType.APPLICATION_JSON).body(service.getEmptyReport(id, defaultName).getChildren().stream().map(r -> (ReportNodeImpl) r).toList());
ok

2024-07-29 06:39 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +                    .body(service.getSubReport(id, severityLevels).getChildren().stream().map(r -> (ReportNodeImpl) r).toList());
ok

2024-07-29 06:39 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/report/server/ReportController.java
> +                ResponseEntity.ok().contentType(MediaType.APPLICATION_JSON).body(subReporters.stream().map(r -> (ReportNodeImpl) r).toList());
ok

2024-07-29 06:40 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/report/server/utils/TestUtils.java
> +    public static void assertReportListsAreEqualIgnoringIds(List<ReportNodeImpl> expectedNodeList, List<ReportNodeImpl> actualNodeList) {
see above

2024-07-29 06:40 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/report/server/ReportControllerTest.java
> +        List<ReportNodeImpl> actualReportNodeList = objectMapper.readValue(result.getResponse().getContentAsString(), new TypeReference<>() { });
No. this doesn't compile ...

2024-07-29 09:00 UTC, Tristan-WorkGH approved these changes

2024-07-29 10:01 UTC, merged